# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-api
  namespace: kubeflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-api
  template:
    metadata:
      labels:
        app: movie-api
    spec:
      containers:
        - name: movie-api
          image: ealen/echo-server
          ports:
            - containerPort: 80