# db-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: movie-db-service
  namespace: kubeflix
spec:
  selector:
    app: movie-db
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP