# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-ui
  namespace: kubeflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-ui
  template:
    metadata:
      labels:
        app: movie-ui
    spec:
      containers:
        - name: movie-ui
          image: abhiabhi03/kubeflix-ui:v1

          ports:
            - containerPort: 80
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: movie-config
                  key: API_URL  